version: "2"
linters:
  enable:
    - depguard
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - nolintlint
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: '`io/ioutil` is deprecated in Go 1.16, use `io` or `os` instead'
    errcheck:
      exclude-functions:
        - io.WriteString(*text/tabwriter.Writer)
    forbidigo:
      forbid:
        - pattern: ^os\.(DirEntry|FileInfo|FileMode|PathError)$
        - pattern: \.Readdir$
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
